execute pathogen#infect()
set nocompatible               " be iMproved                                   
filetype off                   " required!
syntax on
set t_Co=256
" set colorcolumn=80
let mapleader = ","
let maplocalleader = ","
set list listchars=tab:\ \ ,trail:·
set expandtab
set smarttab
set noswapfile
set nobackup
set nowb
set hidden
set autoread
set visualbell
set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000   
set viminfo^=!
set cf
set ai
set si
set cindent
set smartindent
set autoindent
set tabstop=2
set shiftwidth=2
set cinkeys=0{,0},:,0#,!,!^F
set cursorline
set cursorcolumn
set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1
set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

set wildmode=list:longest
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

filetype plugin indent on     " required! 
colorscheme lucius
vmap r "_dP
map <Leader>c :w !ruby -c<cr>
au BufNewFile,BufRead *.rabl set filetype=ruby

" Tips:
" ctrl-w = window stuff, ctrl-w-ctrl-w next win
"          ctrl-ws = split
"          ctrl-wv = split vertic
" "_d      delete to blackhole register, leaves clipboard intact
" mapped r to replace with buffer in visual mode

